/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NextRouteImport } from './routes/next'
import { Route as MobileNotificationsRouteImport } from './routes/_mobile.notifications'
import { Route as MobilePluginsRouteImport } from './routes/_mobile.plugins'
import { Route as UserIdRouteImport } from './routes/user.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NextRoute = NextRouteImport.update({
  id: '/next',
  path: '/next',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileNotificationsRoute = MobileNotificationsRouteImport.update({
  id: '/_mobile/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MobilePluginsRoute = MobilePluginsRouteImport.update({
  id: '/_mobile/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdRoute = UserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/next': typeof NextRoute
  '/notifications': typeof MobileNotificationsRoute
  '/plugins': typeof MobilePluginsRoute
  '/user/$id': typeof UserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/next': typeof NextRoute
  '/notifications': typeof MobileNotificationsRoute
  '/plugins': typeof MobilePluginsRoute
  '/user/$id': typeof UserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/next': typeof NextRoute
  '/_mobile/notifications': typeof MobileNotificationsRoute
  '/_mobile/plugins': typeof MobilePluginsRoute
  '/user/$id': typeof UserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/next' | '/notifications' | '/plugins' | '/user/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/next' | '/notifications' | '/plugins' | '/user/$id'
  id:
    | '__root__'
    | '/'
    | '/next'
    | '/_mobile/notifications'
    | '/_mobile/plugins'
    | '/user/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NextRoute: typeof NextRoute
  MobileNotificationsRoute: typeof MobileNotificationsRoute
  MobilePluginsRoute: typeof MobilePluginsRoute
  UserIdRoute: typeof UserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/next': {
      id: '/next'
      path: '/next'
      fullPath: '/next'
      preLoaderRoute: typeof NextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mobile/notifications': {
      id: '/_mobile/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof MobileNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mobile/plugins': {
      id: '/_mobile/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof MobilePluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id': {
      id: '/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof UserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NextRoute: NextRoute,
  MobileNotificationsRoute: MobileNotificationsRoute,
  MobilePluginsRoute: MobilePluginsRoute,
  UserIdRoute: UserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
